config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "conversations#index"

  # post 'openai/generate_response', to: 'openai#generate_response'

  resources :conversations, only: [:new, :index, :show, :create] do
    resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :messages, dependent: :destroy

  # Instance methods
  def last_message
    messages.parent_type&.last&.content
  end

  def broadcast_last_message(message)
    Turbo::StreamsChannel.broadcast_replace_to(
      "conversation-#{id}-last-message",
      partial: "conversations/chat_list/last_message",
      locals: { last_message: message.content, conversation: self },
      target: "conversation-#{id}-last-message"
    )
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # Associations
  belongs_to :conversation

  belongs_to :parent, class_name: 'Message', foreign_key: :parent_id, optional: true
  has_one :reply, class_name: 'Message', foreign_key: :parent_id

  scope :input_messages, -> { where(parent_id: nil) }

  # Attachements
  has_one_attached :file

  # Scopes
  scope :parent_type, -> { where(parent_id: nil) }

  # Callbacks
  after_create_commit -> { broadcast_message }

  # Instance Methods
  def time_distance
    distance_of_time_in_words(created_at, Time.current)
  end

  def message_date
    created_at.to_date
  end

  def broadcast_message
    MessageBroadcastJob.perform_later(message_id: id)
  end

  def broadcast_content_change
    broadcast_replace_to(
      self,
      partial: "messages/message",
      target: "message-item-#{id}",
      locals: { message: self }
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Devise
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :conversations, dependent: :destroy
  has_many :messages, through: :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_conversation, only: [:show]

  def index
    conversations
  end

  def show
    # Fetching messages of current conversation
    @messages = @conversation.messages.order(created_at: :desc)

    # Fetching other conversations list of current_user to show in left sidebar
    @conversations = current_user.conversations.includes(:messages)
  end

  def create
    @conversation = current_user.conversations.create

    redirect_to conversation_path(@conversation)
  end

  private

  def find_conversation
    # Fetching current conversation
    @conversation ||= conversations.find(params[:id])
  end

  def conversations
    @conversations ||= current_user.conversations.order(created_at: :desc)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = current_user.conversations.find(params[:conversation_id])
    @message      = @conversation.messages.create(message_params)

    @reply        = @message.create_reply(content: 'I am generating your result, please wait!',
                                          conversation: @conversation)

    generate_open_ai_response
  end

  private

  def generate_open_ai_response
    AiResponseJob.perform_later(message_id: @message.id, reply_id: @reply.id)
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/api/tarot/base_helper.rb
module Api::Tarot::BaseHelper
end

app/helpers/api/tarot/cards_helper.rb
module Api::Tarot::CardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/chat_content/_content.html.erb
<turbo-frame
  class="tyn-main tyn-chat-content main-shown"
  id="tynMain"
  data-userid="<%=current_user.id%>"
  data-controller="chat-main"
  data-chat-main-asside-item-id-value="left-side-chat-item-<%= conversation.id %>">

  <%= turbo_stream_from conversation %>

  <!-- User image and name is in this partial -->
  <%= render 'conversations/chat_content/content_head', conversation: conversation %>

  <!-- our chat is in this partial -->
  <%= render 'conversations/chat_content/content_body', conversation: conversation, messages: messages %>

  <!-- The message form is in this partial -->
  <%= render 'conversations/chat_content/content_footer', conversation: conversation %>

  <%= render 'conversations/chat_content/content_sidebar', conversation: conversation %>
  <!-- Right sidebar -->

  <%= render 'conversations/chat_content/scroll_messages', author_id: current_user.id %>

  <turbo-frame id="conversation-message-focus"></turbo-frame>
</turbo-frame>

app/views/conversations/chat_content/_content_body.html.erb
<div class="tyn-chat-body customize_tyn_chat_body" id="tynChatBody" data-controller="messages">
  <div class="tyn-reply" id="tynMessages" data-conversation-id="<%= conversation.id %>">

    <% messages.each do |message| %>
      <%=
        render 'messages/message',
        message: message,
        author_id: message.conversation.user_id
      %>

      <%= render 'messages/date_separator', message: message %>
    <% end %>
  </div>
</div>

app/views/conversations/chat_content/_content_footer.html.erb
<%= render 'messages/form', conversation: conversation %>

app/views/conversations/chat_content/_content_head.html.erb
<div class="tyn-chat-head">
  <ul class="tyn-list-inline d-md-none ms-n1">
    <li>
      <%= link_to conversations_path, data: { turbo_stream: true }, class: 'btn btn-icon btn-md btn-pill btn-transparent js-toggle-main' do %>
        <!-- arrow-left -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
        </svg>
      <% end %>
    </li>
  </ul>

  <%= link_to "#", class: 'tyn-media-group', data: { 'turbo-frame': 'UserModal' } do %>
    
    <div class="tyn-media tyn-size-lg d-none d-sm-inline-flex">
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/1587/1587565.png", alt: "" %>
    </div>
  <% end %>

  <ul class="tyn-list-inline gap gap-3 ms-auto">
    <li class="d-none d-sm-block">
      <button class="btn btn-icon btn-light js-toggle-chat-search">
        <!-- search -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
        </svg>
      </button>
    </li>
  </ul>
</div><!-- .tyn-chat-head -->

app/views/conversations/chat_content/_content_sidebar.html.erb
<div class="tyn-chat-content-aside"
     id="tynChatAside"
     data-summary-conversation-id-value="<%= conversation.id %>"
     data-simplebar>

  <div class="simplebar-content">
    <div class="tyn-media-group tyn-media-vr tyn-media-center mt-n4">
      <div class="tyn-media tyn-size-xl border border-2 border-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-robot" viewBox="0 0 16 16">
          <path d="M6 12.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5ZM3 8.062C3 6.76 4.235 5.765 5.53 5.886a26.58 26.58 0 0 0 4.94 0C11.765 5.765 13 6.76 13 8.062v1.157a.933.933 0 0 1-.765.935c-.845.147-2.34.346-4.235.346-1.895 0-3.39-.2-4.235-.346A.933.933 0 0 1 3 9.219V8.062Zm4.542-.827a.25.25 0 0 0-.217.068l-.92.9a24.767 24.767 0 0 1-1.871-.183.25.25 0 0 0-.068.495c.55.076 1.232.149 2.02.193a.25.25 0 0 0 .189-.071l.754-.736.847 1.71a.25.25 0 0 0 .404.062l.932-.97a25.286 25.286 0 0 0 1.922-.188.25.25 0 0 0-.068-.495c-.538.074-1.207.145-1.98.189a.25.25 0 0 0-.166.076l-.754.785-.842-1.7a.25.25 0 0 0-.182-.135Z"></path>
          <path d="M8.5 1.866a1 1 0 1 0-1 0V3h-2A4.5 4.5 0 0 0 1 7.5V8a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1v1a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-1a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1v-.5A4.5 4.5 0 0 0 10.5 3h-2V1.866ZM14 7.5V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V7.5A3.5 3.5 0 0 1 5.5 4h5A3.5 3.5 0 0 1 14 7.5Z"></path>
        </svg>
      </div>

      <div class="tyn-media-col">
        <div class="tyn-media-row">
          <h6 class="name">Virtual Assistant</h6>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/chat_content/_message_focus.html.erb
<turbo-frame id="conversation-message-focus" data-controller="input-focus"></turbo-frame>

app/views/conversations/chat_content/_scroll_messages.html.erb
<div id="scrollMessages" data-controller="scroll-messages"></div>

app/views/conversations/chat_list/_chat_item.html.erb
<li class="tyn-aside-item js-toggle-main" id="left-side-chat-item">

  <%= link_to conversation_path(conversation), class: 'tyn-media-group', data: { 'turbo-frame': 'tynMain' } do %>
    <div class="tyn-media tyn-size-lg">
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/1587/1587565.png", alt: "" %>
    </div>

    <div class="tyn-media-col">
      <div class="tyn-media-row">
        <%= turbo_stream_from "conversation-#{conversation.id}-last-message" %>
        <%= render 'conversations/chat_list/last_message', last_message: conversation.last_message, conversation: conversation %>
      </div>
    </div>
  <% end %>
</li>

app/views/conversations/chat_list/_chats.html.erb
<turbo-frame class="tyn-aside tyn-aside-base" id="chatsList" data-controller="chats">
  <%= render 'conversations/chat_list/chats_head' %>
  <!-- .tyn-aside-head -->

  <%= render 'conversations/chat_list/chats_body', conversations: conversations %>
  <!-- .tyn-aside-body -->
</turbo-frame>

app/views/conversations/chat_list/_chats_body.html.erb
<div class="tyn-aside-body" data-simplebar>
  <div class="tab-content">
    <div class="tab-pane show active" id="all-chats" tabindex="0" role="tabpanel">
      <ul class="tyn-aside-list" id="aside-chat-list">
        <% @conversations.each do |conversation| %>
          <%= render 'conversations/chat_list/chat_item', conversation: conversation %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/chat_list/_chats_head.html.erb
<div class="tyn-aside-head">
  <div class="tyn-aside-head-text">
    <h3 class="tyn-aside-title">Chats</h3>
  </div>
  <div class="tyn-aside-head-tools">
    <ul class="link-group gap gx-3">
      <li class="dropdown">
        <%= link_to conversations_path, class: 'link', data: { method: :post } do %>
        <!-- <button class="link" data-bs-toggle="modal" data-bs-target="#newChat"> -->
          <!-- plus -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
          </svg>
          <span>New</span>
        <!-- </button> -->
        <% end %>
      </li>
      <!-- li -->
      <li class="dropdown">
        <!-- TODO uncomment to add chat filters -->
        <!-- <button class="link dropdown-toggle" data-bs-toggle="dropdown" data-bs-offset="0,10"> -->
          <!-- filter -->
          <!-- <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filter" viewBox="0 0 16 16"> -->
            <!-- <path d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z" /> -->
          <!-- </svg> -->
          <!-- <span>Filter</span> -->
        <!-- </button> -->
        <div class="dropdown-menu dropdown-menu-end">
          <ul class="tyn-list-links nav nav-tabs border-0">
            <li>
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#all-chats">
                <!-- chat-square-text -->
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                  <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                </svg>
                <span>All Chats</span>
              </button>
            </li>
            <li>
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#active-contacts">
                <!-- person-check -->
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16">
                  <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm1.679-4.493-1.335 2.226a.75.75 0 0 1-1.174.144l-.774-.773a.5.5 0 0 1 .708-.708l.547.548 1.17-1.951a.5.5 0 1 1 .858.514ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
                  <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z" />
                </svg>
                <span>Active Contacts</span>
              </button>
            </li>
            <li>
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#archived-chats">
                <!-- archive -->
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-archive" viewBox="0 0 16 16">
                  <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                </svg>
                <span>Archived Chats</span>
              </button>
            </li>
            <li>
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#spam-messages">
                <!-- bookmark-x -->
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-x" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6.146 5.146a.5.5 0 0 1 .708 0L8 6.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 7l1.147 1.146a.5.5 0 0 1-.708.708L8 7.707 6.854 8.854a.5.5 0 1 1-.708-.708L7.293 7 6.146 5.854a.5.5 0 0 1 0-.708z" />
                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
                </svg>
                <span>Spam Messages</span>
              </button>
            </li>
            <li>
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#trash-bin">
                <!-- trash -->
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                </svg>
                <span>Trash Bin</span>
              </button>
            </li>
          </ul>
          <!-- .nav -->
        </div>
        <!-- .dropdown-menu -->
      </li>
      <!-- li -->
    </ul>
    <!-- .link-group -->
  </div>
  <!-- .tyn-aside-head-tools -->
</div>

app/views/conversations/chat_list/_last_message.html.erb
<h6 class="name" id="conversation-<%= conversation.id %>-last-message"><%= last_message.present? ? last_message : 'New Chat' %></h6>

app/views/conversations/index.html.erb
<turbo-frame class="tyn-content tyn-content-full-height tyn-chat" id="conversationMain">
  <!-- All Chats List -->
  <%= render 'conversations/chat_list/chats', conversations: @conversations %>
</turbo-frame>

app/views/conversations/show.html.erb
<turbo-frame class="tyn-content tyn-content-full-height tyn-chat" id="conversationMain">
	<%= turbo_stream_from @conversation %>
  <%= render 'conversations/chat_list/chats', conversations: @conversations %>

  <%= render 'conversations/chat_content/content', conversation: @conversation, messages: @messages %>
</turbo-frame>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatbot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.theme.default.min.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="tyn-root">
      <%= render 'shared/header' %>
      <%= yield %>

      <div id="image-viewer">
        <span class="close">&times;</span>
        <img class="modal-content" id="full-image">
      </div>

      <turbo-frame id="closeModal"></turbo-frame>
    </div>

    <%= javascript_include_tag "bundle" %>
    <%= javascript_include_tag "app" %>
  </body>
</html>

app/views/messages/_date_separator.html.erb
<div class="tyn-reply-separator d-none" id="message-<%= message.id %>-separator">
  <%= message.created_at.strftime('%b %d, %Y') %>
</div>

app/views/messages/_form.html.erb
<%= form_with(model: [conversation, Message.new],
              class: 'tyn-chat-form',
              data: { controller: 'message-form', 'message-form-conversation-id-value': conversation.id }) do |f| %>

  <div class="tyn-chat-form-enter">
    <%= f.text_field :content, class: 'tyn-chat-form-input', placeholder: 'Type your message...', id: 'tynChatInput' %>

    <ul class="tyn-list-inline me-n2 my-1">
      <li>
        <%= f.button type: :submit, class: 'btn btn-icon btn-white btn-md btn-pill', id: 'send-message-btn' do %>
          <!-- send-fill -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-fill" viewBox="0 0 16 16">
            <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
          </svg>
        <% end %>
      </li>
    </ul>
  </div>
<% end %><!-- .tyn-chat-form -->

app/views/messages/_message.html.erb
<%= turbo_stream_from message %>
<div class="tyn-reply-item <%= message.parent_id.nil? ? 'outgoing' : 'incoming' %>"
     id="message-item-<%= message.id %>"
     data-controller="message-item"
     data-message-item-created-at-value="<%= message.created_at %>"
     data-message-item-message-id-value="<%= message.id %>">

  <div class="tyn-reply-group">
    <span class="message-user-name"></span>

    <div class="tyn-reply-bubble">
      <div class="tyn-reply-text"> <%= raw message.content %> </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="tyn-appbar">
  <div class="container">
    <div class="tyn-appbar-wrap">
      <div class="tyn-appbar-logo">
        <a class="tyn-logo" href="<%= root_path %>">
          <div class="app-logo">Demo</div>
        </a>
      </div>
      <!-- tyn-logo -->
      <div class="tyn-appbar-content">
        <ul class="tyn-appbar-nav tyn-appbar-nav-start">
          <!-- .tyn-appbar-item -->
        </ul>
        <!-- .tyn-appbar-nav -->
        <ul class="tyn-appbar-nav tyn-appbar-nav-end">
          <!-- .tyn-appbar-item -->

          <!-- TODO make notification working -->
          <%#= render 'shared/notification' %>

          <!-- .tyn-appbar-item -->
          
          <!-- Profile dropdown -->
          <% if current_user.present? %>
            <%= render 'shared/profile_dropdown' %>
          <% end %>
          <!-- .tyn-appbar-item -->
        </ul>
        <!-- .tyn-appbar-nav -->
      </div>
      <!-- .tyn-appbar-content -->
    </div>
    <!-- .tyn-appbar-wrap -->
  </div>
</nav>

app/views/shared/_profile_dropdown.html.erb
<li class="tyn-appbar-item" id="profile-dropdown">
  <a class="d-inline-flex dropdown-toggle" data-bs-auto-close="outside" data-bs-toggle="dropdown" href="#" data-bs-offset="0,10">
    <div class="tyn-media tyn-size-lg tyn-circle">
      <%= image_tag 'https://cdn-icons-png.flaticon.com/512/1177/1177568.png', alt:"user-profile" %>
    </div>
  </a>

  <div class="dropdown-menu dropdown-menu-end">
    <div class="dropdown-gap">
      <div class="tyn-media-group">
        <div class="tyn-media tyn-size-lg">
          <%= image_tag 'https://cdn-icons-png.flaticon.com/512/1177/1177568.png', alt:"user-profile" %>
        </div>

        <div class="tyn-media-col">
          <div class="tyn-media-row">
            <h6 class="name"><%= current_user.name %></h6>
            <div class="indicator varified">
            </div>
          </div>
        </div>
      </div>
    </div>
    <ul class="tyn-list-links">
      <li>
        <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false } do %>
          <!-- power -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
            <path d="M7.5 1v7h1V1h-1z" />
            <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
          </svg>
          <span>Log Out</span>
        <% end %>
      </li>
    </ul>
    <!-- .tyn-list-links -->
  </div>
  <!-- .dropdown-menu -->
</li>